### ISSUE TITLE
[US] DRF - Implementing Hashtag Functionality for Posts

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe-frontend#50]
**Statement**:

As a developer, I want to implement tagging functionality for posts so that users can categorize their content.

**Acceptance Criteria**:

- [x] Update the Post model to include tags.
- [x] Add tag input fields to the post creation/editing forms.
- [x] Implement backend logic to handle tags.

**Tasks**:

- [x] Update the Post model to include tags.
- [x] Add tag input fields to the post creation/editing forms.
- [x] Implement backend logic to handle tags.

**Belonging to**:  EPIC -

**Comment by JaqiKal** [comment]
Change wording to 'hashtag '

**Comment by JaqiKal** [comment]
Hashtag Error [BUG#68](https://github.com/JaqiKal/pixavibe-frontend/issues/68)
